# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#top"
  weight = 10

[[main]]
  name = "About"
  url = "#about"
  weight = 20

[[main]]
  name = "Program"
  url = "#2020"
  weight = 21

[[main]]
  name = "Submission"
  url = "#submission"
  weight = 22

[[main]]
  name = "Hackathon"
  url = "#hackathon"
  weight = 23

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 24


[[main]]
  name = "Past Events"
  url = "#experience"
  weight = 30

  [[main]]
    name = "Organizers"
    url = "#people"
    weight = 40

[[main]]
  name = "Subscribe"
  url = "#mailinglist"
 weight = 50


# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 60


[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
